exclude:     ['README.md', 'Gemfile*', 'vendor', 'bin']
markdown: kramdown
source: source
layout: article
permalink: pretty
sass:
    sass_dir: _scss

defaults:
  -
    scope:
      path: "" # match all files in the project
    values:
      layout: article
